---
abstract: 'Plugin to inject before_rendered hook into Mojolicious'
author:
  - 'Companies House <chgovuk@cpan.org>'
build_requires:
  Module::Build: '0.3601'
  Mojolicious::Lite: '0'
  Test::Mojo: '0'
configure_requires:
  Module::Build: '0.3601'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MojoX-Plugin-Hook-BeforeRendered
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Mojo::Base: '0'
  Mojo::Util: '0'
resources:
  bugtracker: https://github.com/companieshouse/MojoX-Plugin-Hook-BeforeRendered/issues
  homepage: https://github.com/companieshouse/MojoX-Plugin-Hook-BeforeRendered
  repository: https://github.com/companieshouse/MojoX-Plugin-Hook-BeforeRendered.git
version: '0.30'
